services:
  app:
    image: storage_backend_test
    container_name: "cloud-storage-server"
    build: ./
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
       SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
       SPRING_DATASOURCE_USERNAME: root
       SPRING_DATASOURCE_PASSWORD: root
       SPRING_JPA_HIBERNATE_DDL_AUTO: update
       SPRING_LIQUIBASE_URL: jdbc:postgresql://db:5432/postgres
       SPRING_LIQUIBASE_USER: root
       SPRING_LIQUIBASE_PASSWORD: root
    networks:
      service1:
  db:
    restart: always
    image: postgres:latest
    container_name: cloud_storage_db
    ports:
      - 7001:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_ROOT_PASSWORD: root
    networks:
      service1:
networks:
  service1:
